### ISSUE TITLE
No "homework" folder listed in directory 

### ISSUE THREAD

**Issue by mwhitfi1** [cfss-fa20/hw01#44]
When I click "Browse," I do not see a "homework" folder I can select. Do we have to create our own homework folder or should it already be in the directory?

**Comment by bensoltoff** [comment]
You don't need a specific folder. This assignment requires you to [edit the `README.md` file](https://cfss.uchicago.edu/homework/edit-readme/), which is already included in the repository.

**Comment by deblnia** [comment]
I’m not sure I understand your question. Have you cloned the homework
repository?

**Comment by mwhitfi1** [comment]
Thank you for clarifying.
