### ISSUE TITLE
About the checklist set by PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by whiskey0504** [cfss-fa20/hw01#55]
Hi, this is not a very Markdown-related question, but I was a little bit confused by the checklist set by PULL_REQUEST_TEMPLATE when trying to submit my pull request. It reminds me to include "R Markdown files, rendered Markdown files," etc, and to make sure my README.md file describes "the purpose of your repository, required packages, location of relevant files, etc."

I'm curious about the difference between "R Markdown files" and "rendered Markdown files," and regarding the second part which I don't think we're asked to address in hw01, I'm wondering if the case is the checklist is not fully updated. Thanks very much in advance!

**Comment by bensoltoff** [comment]
That checklist is generic and is the default for all homework repositories. For the first assignment, you just have a Markdown (`.md`) file. Starting with homework 2, you will be writing code as part of your assignment and editing it in an R Markdown (`.Rmd`) document. You will then "knit" the document to generate a rendered Markdown file which contains the code, output, and all resulting figures/tables. We'll talk more about this during class this week and at office hours.

**Comment by whiskey0504** [comment]
> That checklist is generic and is the default for all homework repositories. For the first assignment, you just have a Markdown (`.md`) file. Starting with homework 2, you will be writing code as part of your assignment and editing it in an R Markdown (`.Rmd`) document. You will then "knit" the document to generate a rendered Markdown file which contains the code, output, and all resulting figures/tables. We'll talk more about this during class this week and at office hours.

Gotcha!! Thanks for the clarification!!!
